# Generated by Django 2.2 on 2019-04-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='First Name', max_length=12)),
                ('lname', models.CharField(default='Last Name', max_length=12)),
                ('profile_image', models.ImageField(default='avatar.png', upload_to='profile')),
                ('cover', models.ImageField(default='cover.png', upload_to='cover')),
                ('bio', models.TextField(default='Your Bio')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('dob', models.CharField(default='DD-MM-YYYY', max_length=12)),
                ('profile_status', models.CharField(max_length=20, verbose_name='Activate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.NewUsers')),
            ],
        ),
    ]
