# Generated by Django 2.2 on 2019-04-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(default='1', max_length=255)),
                ('slug', models.SlugField(default='1', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KartFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=200)),
                ('dish_price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('dish_qty', models.IntegerField(null=True)),
            ],
        ),
    ]
